import Head from "next/head";
import MainSection from "../Components/Main";
import AboutSection from "../Components/About";
import SkillsSection from "../Components/Skills";
import ProjectsSection from "../Components/Projects";
import ContactSection from "../Components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ahmed Adel - Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainSection />
      <AboutSection />
      <SkillsSection />
      <ProjectsSection />
      <ContactSection />
    </div>
  );
}
